name: fanti-data-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - statsmodels
  - jupyter
  - ipywidgets
  - plotly
  - pip
  - pip:
    - jupyter-contrib-nbextensions
    - jupyter-nbextensions-configurator